### ISSUE TITLE
please treat integration tests as optional by default

### ISSUE THREAD

**Issue by jonassmedegaard** [etesync/pyetesync#19]
<README.md> says that "some [tests] are integration tests who need an actual EteSync service with a few user names set up in order for them to work."

Nice that it is documented. Thanks!

Would be even nicer if such tests were treated as optional, at least by default.
Most elegant (that I can imagine) would be to a) try such tests but treat errors as non-fatal unless b) environment variable EXTENDED_TESTING is set.

Why "EXTENDED_TESTING" specifically? Because I see no reason not to reuse the variable already in use in Perl for that exact purpose: https://github.com/Perl-Toolchain-Gang/toolchain-site/blob/master/lancaster-consensus.md

**Comment by tasn** [comment]
I'm happy to do that, but why not use `./run_unit_tests.sh`? That's what ArchLinux use for their packaging.

**Comment by jonassmedegaard** [comment]
because that's custom. What is generic is to execute pytest and let it run all tests.

**Comment by tasn** [comment]
That's fair, but `EXTENDED_TESTING` doesn't look like the right thing either. Looking at the link you provided, this env var is for tests that may be slow and require extra resources, not for ones that require a running server to test against.

**Comment by jonassmedegaard** [comment]
having a local service running _is_ "extra resources"

**Comment by tasn** [comment]
I don't think that's what they mean, I think they mean extra computing resources.

**Comment by jonassmedegaard** [comment]
CPU cycles are indeed resources. If you insist that locally (or remotely) running services are not "resources" then our conversation cannot sensibly continue.

...also, another thing not ideal about your shellscripts is that they hardcode a specific pytest - does not leave room for using a specific Python

**Comment by tasn** [comment]
I'm not insisting, I'm just suggesting that this is what they meant.
Take a look at:
> take extra time or resources to complete
The way it's worded implies that they are referring to computing resources rather than another server. Either way, I don't think we need to over analyse the original text.

Don't get me wrong, I'm happy to change it, I just don't think relying on this env variable is the right way to go. This env variable would be more suitable for e.g. CPU intensive cryptography unit tests than for integration tests.

I'm trying to figure out if there's a better way for doing this. I have an idea that I'm currently taking a look into. I'll report back in a few minutes.

**Comment by tasn** [comment]
I just pushed the fix. It works as you requested, pytest runs only the unit tests by default. In addition, I agree, it makes sense and nicer this way.
Let me know if this what you had in mind, and I'll happily release a new version.

**Comment by jonassmedegaard** [comment]
No, this was not what I had in mind (now _doing_ integration tests requires custom call).

Seems it is not a matter of your missing my point (so I guess it won't help that I try explain it more elaborately), but instead that you disagree with my point (despite your saying that you don't insist you demonstrate persistence in the standpoint you took on that, also reflected in the code changes you did).

If I am mistaken and you would like me to elaborate what I had in mind then please do tell.  Otherwise I will simply respect that this is your project, you do with it as you like.

**Comment by jonassmedegaard** [comment]
sorry, above might come across as grumpy.  I am not grumpy. You are free to handle your project as you like, this issue is a _suggestion_ for you for streamlining how tests are handled.

**Comment by tasn** [comment]
Please explain it more elaborately, it seems that I don't understand you then.
I was attempting to fix the original bug reported, which was:
> Would be even nicer if such tests were treated as optional, at least by default.

As I elaborated in [my other comment](https://github.com/etesync/pyetesync/issues/19#issuecomment-607270192), I don't think this is the right environment variable for this. We seem to disagree on that, but I don't think this affects the core of the report (`pytest` running integration tests by default), which is what I was attempting to fix.

**Comment by jonassmedegaard** [comment]
The project includes 3 test files. It is "optional" to execute any or all or none of those, if picking them individually, as is done with the custom shell scripts.

What I suggest with having them "treated as optional" is to tell _pytest_ that they are optional.  One way to do that is to flag them as non-fatal, so that they are always tried but failing the test does not cause the whole testsuite to be considered failed.  Another more elegant way is to run them conditional to an environment flag.

Your code change told pytest to always omit them. I wouldn't call that optional (yes it is optional in the sense that having pytest make you a sandwich is optional: you can explicitly call pytest and tell it to execute an arbitrary custom test file - similar to how you did already, just inverse).

**Comment by tasn** [comment]
Non-fatal is a no-go, because we do want them to be fatal, for people developing pyetesync. Just not for people running the unit tests (e.g. packagers).
Env var: yeah, that's another path we can take, we can make pytest skip all of the integration tests unless an env var is set. I don't mind doing that, but I'm against using the aforementioned env var for it. I can use `INTEGRATION_TESTING` (or TESTS).

While my code does tell pytest to always omit them, the intention (and in practice what is happening) is that the integration tests are now considered a different test suite, that should be called differently. It's another approach to solving it.

Anyhow, I really don't mind other way when it comes to env vs the above. What I disagree with is only reusing that env variable which as I already explained, I don't think is suitable for this case.

**Comment by jonassmedegaard** [comment]
so you _insist_ on your interpretation that CPU cycles is the _only_ resource meant by the existing formally defined environment variable, and therefore find it better to invent your own?

**Comment by jonassmedegaard** [comment]
(hint: try check the documentation for the two implementations of the Lancaster consensus environment variables)

**Comment by jonassmedegaard** [comment]
if you don't want to follow existing convention but instead will invent your own custom logic, then I recommend to *not* change anything: Current custom logic is just as good as another custom one!

**Comment by tasn** [comment]
> so you _insist_ on your interpretation that CPU cycles is the _only_ resource meant by the existing formally defined environment variable, and therefore find it better to invent your own?

The same way you insist your interpretation is right. This line of reasoning goes both ways.

> (hint: try check the documentation for the two implementations of the Lancaster consensus environment variables)

I don't know what you are referring to.

In addition to the above, let me further clarify my thoughts on this topic. I'm more than happy to follow a standard/convention when there is an established one. However, in addition to my objections above, I don't consider Perl (is this even the official Perl stance?) as the absolute authority on things. The fact that someone (or a few someones or heck, even many someones) do something doesn't make something a convention or a best practice. Especially not when they constitute a very small amount of the population.

It's possible that I'm wrong and making the wrong call here, but it's also possible that you are wrong. End of the day though, it's really not that big of a deal, and doesn't affect the Debian packaging as you won't be running the integration tests anyway...

**Comment by jonassmedegaard** [comment]
I insist that the definition is suitable - and am willing to back it up by others documenting how it is supposed to be interpreted.

You insist that the definition is unsuitable - and absurdly claim that you are not insisting, despite continued argumentation based only on your own personal reasoning, and despite your refusal to let go of your standpoint.

**Comment by jonassmedegaard** [comment]
For the record, I do expect to run the integration tests.  This issue is about streamlining how to express testing (oh wait, I already wrote that, so why would I need to repeat myself?)

**Comment by tasn** [comment]
> I insist that the definition is suitable - and am willing to back it up by others documenting how it is supposed to be interpreted.

I'd be happy to see it, though a random person on the internet thinking the same of you won't change my opinion on this.

> 
> You insist that the definition is unsuitable - and absurdly claim that you are not insisting, despite continued argumentation based only on your own personal reasoning, and despite your refusal to let go of your standpoint.

I have grammar on my side. I concede, that maybe the original author was not a native speaker and actually meant what you understand, though that doesn't matter. As I said, that doesn't matter because even if this text was very clear about what should be done, it is not the authority of the world. Do all the packages in Debian follow this? No. Do 50% of them? No. Do 10%? Maybe, but unlikely. So I don't get this insistence.

> For the record, I do expect to run the integration tests. This issue is about streamlining how to express testing (oh wait, I already wrote that, so why would I need to repeat myself?)

Scroll back, you actually didn't. Though even if you did, I'm talking about Debian, as in the package, not you. I've had to repeat myself a million times in this thread too.

I think we are getting nowhere with this, and it's best to cool off for 24 hrs before we continue discussing it.

**Comment by tasn** [comment]
I've given it some more thought, and I realised, that while I still stand behind all of the above, I don't think it matters enough to continue arguing over this. It seems like it's very important to you to have this variable named exactly like this, and while I disagree with both the interpretation and the authority of the source, at the end of the day, it doesn't really matter.

Let me know if that's what you had in mind.

**Comment by jonassmedegaard** [comment]
What I had in my was indeed to reuse a hinting mechanism insread of rolling your own custom one - not because of any authority of that other one over you but to limit the amount of unique custom bits in the World of code: Some of your users never use Perl and therefore they won't benefit from reusing a mechanism popular in the Perl community, but some do and they will.
